-- Modèle physique de données (MLD / DDL)
-- Compatible avec H2 / PostgreSQL pour l'application Spring Boot actuelle

CREATE TABLE categorie (
    id_categorie BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_categorie VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE marque (
    id_marque BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_marque VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ingredient (
    id_ingredient BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_ingredient VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE allergene (
    id_allergene BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_allergene VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE additif (
    id_additif BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_additif VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE produit (
    id_produit BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_produit VARCHAR(255) NOT NULL,
    score_nutritionnel VARCHAR(1),
    energie DECIMAL(12, 2),
    matiere_grasse DECIMAL(10, 2),
    categorie_id BIGINT NOT NULL,
    marque_id BIGINT NOT NULL,
    CONSTRAINT fk_produit_categorie
        FOREIGN KEY (categorie_id) REFERENCES categorie(id_categorie),
    CONSTRAINT fk_produit_marque
        FOREIGN KEY (marque_id) REFERENCES marque(id_marque)
);

CREATE TABLE produit_ingredient (
    id_produit BIGINT NOT NULL,
    id_ingredient BIGINT NOT NULL,
    PRIMARY KEY (id_produit, id_ingredient),
    CONSTRAINT fk_pi_produit
        FOREIGN KEY (id_produit) REFERENCES produit(id_produit),
    CONSTRAINT fk_pi_ingredient
        FOREIGN KEY (id_ingredient) REFERENCES ingredient(id_ingredient)
);

CREATE TABLE produit_allergene (
    id_produit BIGINT NOT NULL,
    id_allergene BIGINT NOT NULL,
    PRIMARY KEY (id_produit, id_allergene),
    CONSTRAINT fk_pa_produit
        FOREIGN KEY (id_produit) REFERENCES produit(id_produit),
    CONSTRAINT fk_pa_allergene
        FOREIGN KEY (id_allergene) REFERENCES allergene(id_allergene)
);

CREATE TABLE produit_additif (
    id_produit BIGINT NOT NULL,
    id_additif BIGINT NOT NULL,
    PRIMARY KEY (id_produit, id_additif),
    CONSTRAINT fk_pad_produit
        FOREIGN KEY (id_produit) REFERENCES produit(id_produit),
    CONSTRAINT fk_pad_additif
        FOREIGN KEY (id_additif) REFERENCES additif(id_additif)
);

CREATE INDEX idx_produit_categorie ON produit(categorie_id);
CREATE INDEX idx_produit_marque ON produit(marque_id);
CREATE INDEX idx_produit_nom ON produit(nom_produit);
CREATE INDEX idx_produit_score ON produit(score_nutritionnel);
